FROM --platform=linux/amd64 eclipse-temurin:19-jre-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/springboot-app-*.jar
COPY ${JAR_FILE} /app/springboot-app.jar
ENTRYPOINT ["java","-jar","/app/springboot-app.jar"]
EXPOSE 8703
